name: Build Flutter Windows App

on:
  push:
    branches:
      - main # Запускать этот workflow при каждом push в ветку main

jobs:
  build:
    runs-on: windows-latest # Запускаем на виртуальной машине с последней версией Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Клонируем репозиторий

      - name: Setup Flutter
        uses: subosito/flutter-action@v2 # Устанавливаем Flutter SDK
        with:
          flutter-version: '3.38.2' # Укажи здесь точную версию Flutter, которую ты используешь
          channel: 'stable'

      # Теперь используем 'working-directory' для каждого шага
      # Это указывает GitHub Actions, где именно выполнять команду
      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: sales_analytics_app # <--- УКАЗЫВАЕМ ПУТЬ К ПРОЕКТУ

      - name: Enable Windows Desktop support (if not already enabled)
        run: flutter config --enable-windows-desktop
        working-directory: sales_analytics_app # <--- УКАЗЫВАЕМ ПУТЬ К ПРОЕКТУ

      - name: Build Windows Release
        run: flutter build windows --release
        working-directory: sales_analytics_app # <--- УКАЗЫВАЕМ ПУТЬ К ПРОЕКТУ

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-build
          path: sales_analytics_app/build/windows/x64/release/runner # <--- ПУТЬ К АРТЕФАКТАМ ОТ КОРНЯ РЕПО
          retention-days: 7
